name: Deploy to WordPress.org

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Run Build and Release Package Script
      run: npm run release:package

    - name: Deploy WordPress Plugin
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SLUG: advajra
        BUILD_DIR: .release/advajra
